package Project;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Random;

public class New_Customer extends JFrame implements ActionListener {
    JTextField tname,taddress,tcity,tstate,temail,tphone;
    JButton next,cancel;
    JLabel autogeneratedmeterno;
    New_Customer()
    {
        setLocation(400,50);
    setSize(600,500);
        JPanel p=new JPanel();
        p.setLayout(null);
        p.setBackground(new Color(173,216,230));
        add(p);

        JLabel heading =new JLabel("New Customer");
        heading.setBounds(160,5,200,20);
        heading.setFont(new Font("Tahona",Font.PLAIN,24));
        p.add(heading);

        JLabel cname =new JLabel("Customer Name");
        cname.setBounds(50,55,200,20);
        p.add(cname);

        tname= new JTextField();
        tname.setBounds(170,55,200,20);
        p.add(tname);

        JLabel jmeterno =new JLabel("Meter Number");
        jmeterno.setBounds(50,100,200,20);
        p.add(jmeterno);

         autogeneratedmeterno =new JLabel("");
        autogeneratedmeterno.setBounds(170,100,200,20);
        p.add(autogeneratedmeterno);

        Random ran=new Random();
        long number=ran.nextLong()%1000000;
        autogeneratedmeterno.setText(""+Math.abs(number)+"");

        JLabel jaddress =new JLabel("Address");
        jaddress.setBounds(50,140,200,20);
        p.add(jaddress);

        taddress= new JTextField();
        taddress.setBounds(170,140,200,20);
        p.add(taddress);

        JLabel jcity =new JLabel("City");
        jcity.setBounds(50,180,200,20);
        p.add(jcity);

        tcity= new JTextField();
        tcity.setBounds(170,180,200,20);
        p.add(tcity);

        JLabel jstate =new JLabel("State");
        jstate.setBounds(50,220,200,20);
        p.add(jstate);

        tstate= new JTextField();
        tstate.setBounds(170,220,200,20);
        p.add(tstate);

        JLabel jemail =new JLabel("Email");
        jemail.setBounds(50,260,200,20);
        p.add(jemail);

        temail= new JTextField();
        temail.setBounds(170,260,200,20);
        p.add(temail);

        JLabel jphone =new JLabel("Phone Number");
        jphone.setBounds(50,300,200,20);
        p.add(jphone);

        tphone= new JTextField();
        tphone.setBounds(170,300,200,20);
        p.add(tphone);

        next =new JButton("Next");
        next.setBounds(70,370,100,25);
        next.setBackground(Color.BLACK);
        next.setForeground(Color.WHITE);
        next.addActionListener(this);
        p.add(next);

        cancel =new JButton("Cancel");
        cancel.setBounds(210,370,100,25);
        cancel.setBackground(Color.BLACK);
        cancel.setForeground(Color.WHITE);
        cancel.addActionListener(this);
        p.add(cancel);

        add(p,"Center");
        ImageIcon i=new ImageIcon(ClassLoader.getSystemResource("hicon1.jpg"));
        Image i1=i.getImage().getScaledInstance(150,300,Image.SCALE_DEFAULT);
        ImageIcon i2=new ImageIcon(i1);
        JLabel img=new JLabel(i2);
        add(img,"West");
          getContentPane().setBackground(Color.WHITE);

        setVisible(true);
    }
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == next) {
            String name=tname.getText();
            String address=taddress.getText();
            String meter=autogeneratedmeterno.getText();
            String city=tcity.getText();
            String state=tstate.getText();
            String email=temail.getText();
            String phone_no=tphone.getText();
            String query1="insert into customer values ('"+name+"','"+meter+"','"+address+"','"+city+"','"+state+"','"+email+"','"+phone_no+"')";
            String query2="insert into login values ('"+meter+"','','"+name+"','','')";
            try {
                Connect c=new Connect();
                c.s.executeUpdate(query1);
                c.s.executeUpdate(query2);

                JOptionPane.showMessageDialog(null,"Customer Details added Successfully");
                setVisible(false);
                new meterinfo(meter);

            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        } else
        {
            setVisible(false);
        }
    }
    public static void main(String[] args)
    {

        new New_Customer();
    }
}
